### ISSUE TITLE
Crashes in ST3 

### ISSUE THREAD

**Issue by dflamholc** [Valkaari/CINEMA4D-Py_dev.sublime-package#11]
Not really sure how to use this. I've cloned the repo into my ST3 Packages folder.
I see Cinema4d (.res Description) and Cinema4d Python API, as available syntaxes, but the API crashes ST3. Any advice or instructions much appreciated ;) thx David

**Comment by Valkaari** [comment]
in the cinema4D_pythonAPI.YAML-tmLanguage file, I've truncated the variables lines into 4 groups. There was an issu with ST2, maybe it's the same problem. Could you give it a try ?
