### ISSUE TITLE
APPCRASH

### ISSUE THREAD

**Issue by dixiony** [Valkaari/CINEMA4D-Py_dev.sublime-package#5]
I choose the syntax "Cinema4d Python API" and get an error message (sorry, the system in Russian):
http://i.imgur.com/oMT11n3.jpg

Windows 7 64, Sublime Text 3 Build 3126

**Comment by Valkaari** [comment]
it's not working as good as it should anyway. i'll try to update it one asap but for now, let's call it deprecated.

**Comment by dixiony** [comment]
Well, I'll wait for the update.

**Comment by oinon** [comment]
hello,
I will wait, too.
Work fine on sublime text2.
https://www.sublimetext.com/2

I did recording video ago few days. and introduced your api.
http://oinon.net/blog/how-to-set-up-editor-for-cinema-4d-python/

Thank you for share.

**Comment by dixiony** [comment]
I understood what was happening. A string with constants (for example, AACTION_OP_LESSTHAN, etc.) is too long and therefore the program fails. I truncated this line to five constants and it immediately earned.

**Comment by Valkaari** [comment]
nice oinon. I need to update this package to R18...

**Comment by Valkaari** [comment]
i've updated the package to the R18 documentation. But i didn't truncated the constants line.
